version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8480:80"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - signaling

  signaling:
    build:
      context: .
      dockerfile: Dockerfile.signaling
    ports:
      - "8481:3001"
    env_file:
      - .env
    restart: unless-stopped
